import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

import { TanstackProvider } from '@/providers/tanstack-provider';
import Navbar from '@/components/navbar';

const poppins = Poppins({
  weight: ['400', '500', '600'],
  subsets: ['latin'],
  variable: '--font-poppins',
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <Navbar />
        <TanstackProvider>{children}</TanstackProvider>
      </body>
    </html>
  );
}
