version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-backend
    ports:
      - "4000:4000"
    volumes:
      - ./:/app

  frontend:
    build:
      context: ./frontend
      target: dev
      dockerfile: Dockerfile-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

    depends_on:
      - database

  database:
    image: alpine:latest
    volumes:
      - ./internal/db/sqlite:/data
    command: sh -c "apk --no-cache add sqlite && if [ ! -f /data/database.db ]; then touch /data/database.db; fi && tail -f /dev/null"
