FROM alpine:latest

RUN apk --no-cache add sqlite

# Create a directory to store the database
WORKDIR /db

# Copy your SQLite database file into the container
COPY internal/db/sqlite/initial-db.sqlite .
# Expose the port if needed
# EXPOSE 1433
# Command to run when the container starts
CMD ["sqlite3", "/data/initial-db.sqlite"]