version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-backend
    ports:
      - "4000:4000"
    volumes:
      - ./:/app

  frontend:
    build:
      context: ./frontend
      target: dev
      dockerfile: Dockerfile-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"