version: '3.8'
services:
  frontend:
    image: social-network-fe
    build:
      context: frontend/
      target: dev
      dockerfile: Dockerfile-frontend
    volumes:
        - ./frontend:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"