FROM golang:1.22

ENV GOFLAGS="-buildvcs=false"

# Environment variables which CompileDaemon requires to run
ENV PROJECT_DIR=/app \
    GO111MODULE=on

WORKDIR /app
COPY . .

RUN go mod download -x

RUN mkdir /appbin

# Get CompileDaemon
RUN go get github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon --build="go build -o /appbin/main ./cmd/api" --command="/appbin/main"