FROM alpine:latest

RUN apk --no-cache add sqlite

# Create a directory to store the database
WORKDIR /db

# Copy your SQLite database file into the container
COPY internal/db/sqlite/initial-database.db .
# Expose the port if needed
# EXPOSE 5432
# Command to run when the container starts
CMD ["sqlite3", "/data/initial-database.db"]