FROM golang:1.22

ENV GOFLAGS="-buildvcs=false"

# Environment variables which CompileDaemon requires to run
ENV PROJECT_DIR=/app \
    GO111MODULE=on

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download -x

COPY . .

RUN mkdir /appbin

# Get CompileDaemon
RUN go get github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon

# Get gorilla/websocket
RUN go get github.com/gorilla/websocket
RUN go install github.com/gorilla/websocket

ENTRYPOINT CompileDaemon --build="go build -o /appbin/main ./cmd/api" --command="/appbin/main"